### ISSUE TITLE
Is it possible to add loading indicator ?

### ISSUE THREAD

**Issue by nkostadinov** [quill-mention/quill-mention#69]
Is it possible to add loading indicator to the dropdown menu while the matches are being loaded from remote source ? it will be really usefull.

**Comment by silentsnooc** [comment]
I think one way to do it is to return some "loading state" objects and use `renderItem` to decide how to render each item.

Similar to the action button:

```js
renderItem: (item, searchTerm) => {
  if (item.hasOwnProperty('query')) {
    return `
      <div class="cql-list-item-action">
        "<i>${item.query}</i>" erstellen
      </div>`;
  }
  return `<div class="cql-list-item-inner">${item.value}</div>`;
}
```

but instead of looking for a property `query` you  could just use an arbitrary indicator to decide whether to  render a loading indicator item or something like that.
